apiVersion: llmnetes.dev/v1alpha1
kind: Command
metadata:
  name: my-command
  annotations:
    yolo.ahilaly.dev/llm-backend: "claude3" # open api
spec:
  input: Create 3 nginx pods that will serve traffic on port 80.xw