# permissions for end users to edit chaossimulations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: chaossimulation-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: yolo-operator
    app.kubernetes.io/part-of: yolo-operator
    app.kubernetes.io/managed-by: kustomize
  name: chaossimulation-editor-role
rules:
- apiGroups:
  - batch.yolo.ahilaly.dev
  resources:
  - chaossimulations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.yolo.ahilaly.dev
  resources:
  - chaossimulations/status
  verbs:
  - get
