# permissions for end users to view commandexecs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: commandexec-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: yolo-operator
    app.kubernetes.io/part-of: yolo-operator
    app.kubernetes.io/managed-by: kustomize
  name: commandexec-viewer-role
rules:
- apiGroups:
  - llmnetes.dev
  resources:
  - commandexecs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - llmnetes.dev
  resources:
  - commandexecs/status
  verbs:
  - get
