---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - batch.yolo.ahilaly.dev
  resources:
  - chaossimulations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.yolo.ahilaly.dev
  resources:
  - chaossimulations/finalizers
  verbs:
  - update
- apiGroups:
  - batch.yolo.ahilaly.dev
  resources:
  - chaossimulations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch.yolo.ahilaly.dev
  resources:
  - clusteraudits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.yolo.ahilaly.dev
  resources:
  - clusteraudits/finalizers
  verbs:
  - update
- apiGroups:
  - batch.yolo.ahilaly.dev
  resources:
  - clusteraudits/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch.yolo.ahilaly.dev
  resources:
  - commandexecs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.yolo.ahilaly.dev
  resources:
  - commandexecs/finalizers
  verbs:
  - update
- apiGroups:
  - batch.yolo.ahilaly.dev
  resources:
  - commandexecs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch.yolo.ahilaly.dev
  resources:
  - commands
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.yolo.ahilaly.dev
  resources:
  - commands/finalizers
  verbs:
  - update
- apiGroups:
  - batch.yolo.ahilaly.dev
  resources:
  - commands/status
  verbs:
  - get
  - patch
  - update
