# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/batch.yolo.ahilaly.dev_commands.yaml
- bases/batch.yolo.ahilaly.dev_commandexecs.yaml
- bases/batch.yolo.ahilaly.dev_chaossimulations.yaml
- bases/batch.yolo.ahilaly.dev_clusteraudits.yaml
- bases/batch.yolo.ahilaly.dev_cvescans.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- path: patches/webhook_in_commands.yaml
#- path: patches/webhook_in_commandexecs.yaml
#- path: patches/webhook_in_chaossimulations.yaml
#- path: patches/webhook_in_clusteraudits.yaml
#- path: patches/webhook_in_cvescans.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- path: patches/cainjection_in_commands.yaml
#- path: patches/cainjection_in_commandexecs.yaml
#- path: patches/cainjection_in_chaossimulations.yaml
#- path: patches/cainjection_in_clusteraudits.yaml
#- path: patches/cainjection_in_cvescans.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
